base_url = "https://www.jasperdunn.com"
title = "Jasper Dunn"
description = "My thoughts on software development."
default_language = "en"

build_search_index = true
compile_sass = true

taxonomies = [
    {name = "categories", paginate_by = 5},
    {name = "tags", paginate_by = 5},
]

[markdown]
highlight_code = true
highlight_theme = "one-dark"

external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

smart_punctuation = true

[extra]
# Put all your custom variables here